name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Compile Go stdlib for Darwin
        run: go install -v std
        env:
          GOOS: darwin

      - name: Set Please overrides
        run: echo "::set-env name=PLZ_OVERRIDES::go.goroot:$GOROOT"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Goroot
        run: ./pleasew run :goroot

      - name: Build
        run: ./pleasew build //...

      - name: Test
        run: ./pleasew test //...

      - name: Save Please log output
        uses: actions/upload-artifact@v1
        with:
          name: build-log
          path: plz-out/log

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run linter
        run: ./pleasew lint
