name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=readonly
      PLZ_ARGS: -p

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Compile Go stdlib for Darwin
        run: go install -v std
        env:
          GOOS: darwin

      - name: Set Please overrides
        run: echo "::set-env name=PLZ_OVERRIDES::build.path:$PATH"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

      - name: Publish
        run: ./pleasew $PLZ_ARGS publish -m "${{ steps.get_version.outputs.tag }}" ${{ steps.get_version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save Please log output
        uses: actions/upload-artifact@v1
        with:
          name: release-log
          path: plz-out/log
