name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

      - name: Publish
        run: ./pleasew publish -m "${{ steps.get_version.outputs.tag }}" ${{ steps.get_version.outputs.tag }}
